### ISSUE TITLE
Parsing error using + combinator

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-nesting#67]
Hi Jonathan, i have the following issue using the `@nest` at-rule.

Using the `>` combinator inside a `@nest` selector it works fine. This snippet works as expected:

```css
.Hint {
  color: blue

  @nest .Field:invalid > & {
    color: red;
  }
}

/*
	RETURNS
	.Hint {
	  color: blue
	}
	
	.Field:invalid > .Hint {
	    color: red;
	}
*/
```

But this returns a syntax error:

```css
.Hint {
  color: blue

  @nest .Field:invalid + & {
    color: red;
  }
}

/*
	SHOULD RETURNS
	.Hint {
	  color: blue
	}
	
	.Field:invalid + .Hint {
	    color: red;
	}
*/
```

> Module build failed: ParserError: Syntax Error at line: 1, column 16 at Generator.next (<anonymous>)

Now i know i could write the selector in another way to make it work, but i think it's just a sort of parsing bug because both are valid combinators, and i want to keep consistency using one syntax (using @nest).
