### ISSUE TITLE
Combinators in nested selector not being parsed

### ISSUE THREAD

**Issue by Stopa** [csstools/postcss-nesting#85]
Minimal test case:

```css
li {
  & + & {
    background: red;
  }
}
```

Expected result:

```css
li + li {
  background: red;
}
```

Actual result:

```css
li {
  & + & {
    background: red;
  }
}
```

Same happens with direct child combinator (`>`) and general sibling combinator (`~`).

I wasn't sure if this use case is covered in the CSS nesting spec, but as far as I can tell there's no reason why it shouldn't be - the nested selector starts with an ampersand and cases like `&&` are supported, so I assume this should be as well. As you can see, the transforming of these selectors is simply ignored.

Versions:
postcss: 8.3.9
postcss-nesting: 8.0.1

Workaround:
For now, using `@nest` seems to work

```css
li {
  @nest & + & {
    background: red;
  }
}
```

transforms to:

```css
:is(li) + :is(li) {
  background: red;
}
```

which is not ideal, but acceptable
